[package]
name = "lemmy_email"
publish = false
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "lemmy_email"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
lemmy_utils = { workspace = true, features = ["full"] }
lemmy_db_schema = { workspace = true, features = ["full"] }
lemmy_db_views_local_user = { workspace = true, features = ["full"] }
lemmy_db_schema_file = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
rosetta-i18n = { workspace = true }
html2text = { workspace = true }
lettre = { version = "0.11.17", default-features = false, features = [
  "builder",
  "smtp-transport",
  "tokio1-rustls-tls",
  "pool",
] }

[dev-dependencies]

[build-dependencies]
rosetta-build = { version = "0.1.3", default-features = false }
