[package]
name = "lemmy_apub_lib_derive"
version = "0.12.2-rc.1"
edition = "2018"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = { version = "1.0.45", features = ["diff"] }

[dependencies]
proc-macro2 = "1.0.28"
syn = "1.0.75"
quote = "1.0.9"
