[package]
name = "lemmy_db_views_person_liked_combined"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[features]
full = [
  "lemmy_utils",
  "diesel",
  "diesel-async",
  "i-love-jesus",
  "lemmy_db_schema/full",
  "lemmy_db_schema_file/full",
  "lemmy_diesel_utils/full",
  "lemmy_db_views_post_comment_combined/full",
]
ts-rs = [
  "dep:ts-rs",
  "lemmy_db_schema/ts-rs",
  "lemmy_db_views_post_comment_combined/ts-rs",
]

[dependencies]
lemmy_db_views_post_comment_combined = { workspace = true }
lemmy_db_views_local_user = { workspace = true }
lemmy_db_schema = { workspace = true }
lemmy_utils = { workspace = true, optional = true }
lemmy_db_schema_file = { workspace = true }
lemmy_diesel_utils = { workspace = true }
diesel = { workspace = true, optional = true }
diesel-async = { workspace = true, optional = true }
serde = { workspace = true }
serde_with = { workspace = true }
ts-rs = { workspace = true, optional = true }
i-love-jesus = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
serial_test = { workspace = true }
tokio = { workspace = true }
