[package]
name = "lemmy_api_crud"
version = "0.14.5-rc.2"
edition = "2018"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"
homepage = "https://join-lemmy.org/"
documentation = "https://join-lemmy.org/docs/en/index.html"

[dependencies]
lemmy_apub = { version = "=0.14.5-rc.2", path = "../apub" }
lemmy_apub_lib = { version = "=0.14.5-rc.2", path = "../apub_lib" }
lemmy_utils = { version = "=0.14.5-rc.2", path = "../utils" }
lemmy_db_schema = { version = "=0.14.5-rc.2", path = "../db_schema" }
lemmy_db_views = { version = "=0.14.5-rc.2", path = "../db_views" }
lemmy_db_views_moderator = { version = "=0.14.5-rc.2", path = "../db_views_moderator" }
lemmy_db_views_actor = { version = "=0.14.5-rc.2", path = "../db_views_actor" }
lemmy_api_common = { version = "=0.14.5-rc.2", path = "../api_common" }
lemmy_websocket = { version = "=0.14.5-rc.2", path = "../websocket" }
diesel = "1.4.8"
bcrypt = "0.10.1"
chrono = { version = "0.4.19", features = ["serde"] }
serde_json = { version = "1.0.68", features = ["preserve_order"] }
serde = { version = "1.0.130", features = ["derive"] }
actix = "0.12.0"
actix-web = { version = "4.0.0-beta.9", default-features = false }
actix-rt = { version = "2.2.0", default-features = false }
awc = { version = "3.0.0-beta.8", default-features = false }
tracing = "0.1.29"
rand = "0.8.4"
strum = "0.21.0"
strum_macros = "0.21.1"
url = { version = "2.2.2", features = ["serde"] }
openssl = "0.10.36"
http = "0.2.5"
http-signature-normalization-actix = { version = "0.5.0-beta.10", default-features = false, features = ["sha-2"] }
base64 = "0.13.0"
tokio = "1.12.0"
futures = "0.3.17"
itertools = "0.10.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
sha2 = "0.9.8"
async-trait = "0.1.51"
anyhow = "1.0.44"
thiserror = "1.0.29"
background-jobs = "0.11.0"
reqwest = { version = "0.11.4", features = ["json"] }
webmention = "0.4.0"
