[package]
name = "lemmy_db_views_moderator"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
lemmy_db_queries = { path = "../db_queries" }
lemmy_db_schema = { path = "../db_schema" }
diesel = { version = "1.4.5", features = ["postgres","chrono","r2d2","serde_json"] }
serde = { version = "1.0.123", features = ["derive"] }
