version: '3.3'

services:
  lemmy_db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - lemmy_db:/var/lib/postgresql/data
    restart: always
  lemmy:
    image: dessalines/lemmy:v0.5.15
    ports:
      - "127.0.0.1:8536:8536"
    restart: always
    volumes:
      - ./lemmy.hjson:/config/config.hjson:ro
    depends_on:
      - lemmy_db
  lemmy_pictshare:
    image: shtripok/pictshare:latest
    ports:
      - "127.0.0.1:8537:80"
    volumes:
      - lemmy_pictshare:/usr/share/nginx/html/data
    restart: always
volumes:
  lemmy_db:
  lemmy_pictshare:
