[package]
name = "lemmy_db_views_notification"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[features]
full = [
  "lemmy_utils",
  "diesel",
  "diesel-async",
  "i-love-jesus",
  "lemmy_db_schema/full",
  "lemmy_db_schema_file/full",
  "lemmy_db_views_private_message/full",
  "lemmy_db_views_post/full",
  "lemmy_db_views_comment/full",
  "lemmy_db_views_modlog/full",
  "lemmy_db_views_notification_sql",
]
ts-rs = ["dep:ts-rs", "lemmy_db_schema/ts-rs"]

[dependencies]
lemmy_db_schema = { workspace = true }
lemmy_utils = { workspace = true, optional = true }
lemmy_db_schema_file = { workspace = true }
lemmy_db_views_private_message = { workspace = true }
lemmy_db_views_post = { workspace = true }
lemmy_db_views_comment = { workspace = true }
lemmy_db_views_modlog = { workspace = true }
lemmy_db_views_notification_sql = { workspace = true, optional = true }
lemmy_diesel_utils = { workspace = true }
diesel = { workspace = true, optional = true }
diesel-async = { workspace = true, optional = true }
serde = { workspace = true }
ts-rs = { workspace = true, optional = true }
i-love-jesus = { workspace = true, optional = true }
serde_with = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
tokio = { workspace = true }
pretty_assertions = { workspace = true }
