version: '3.3'

services:
  lemmy:
    image: {{ lemmy_docker_image }}
    ports:
      - "127.0.0.1:8536:8536"
    restart: always
    volumes:
      - ./lemmy.hjson:/config/config.hjson:ro
    depends_on:
      - postgres
      - pictshare
      - iframely

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD={{ postgres_password }}
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  pictshare:
    image: shtripok/pictshare:latest
    ports:
      - "127.0.0.1:8537:80"
    volumes:
      - ./volumes/pictshare:/usr/share/nginx/html/data
    restart: always

  iframely:
    image: dogbin/iframely:latest
    ports:
      - "127.0.0.1:8061:80"
    volumes:
      - ./iframely.config.local.js:/iframely/config.local.js:ro
    restart: always

  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname={{ domain }}
    restart: "always"