[package]
name = "lemmy_websocket"
version = "0.16.5"
edition = "2021"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"
homepage = "https://join-lemmy.org/"
documentation = "https://join-lemmy.org/docs/en/index.html"
rust-version = "1.57"

[lib]
name = "lemmy_websocket"
path = "src/lib.rs"
doctest = false

[dependencies]
lemmy_utils = { version = "=0.16.5", path = "../utils" }
lemmy_api_common = { version = "=0.16.5", path = "../api_common", features = ["full"] }
lemmy_db_schema = { version = "=0.16.5", path = "../db_schema", features = ["full"] }
lemmy_db_views = { version = "=0.16.5", path = "../db_views", features = ["full"] }
lemmy_db_views_actor = { version = "=0.16.5", path = "../db_views_actor", features = ["full"] }
reqwest-middleware = "0.1.5"
tracing = "0.1.32"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.79", features = ["preserve_order"] }
actix = "0.13.0"
anyhow = "1.0.56"
diesel = "1.4.8"
background-jobs = "0.12.0"
tokio = "1.17.0"
strum = "0.24.0"
strum_macros = "0.24.0"
chrono = { version = "0.4.19", features = ["serde"], default-features = false }
actix-web = { version = "4.0.1", default-features = false, features = ["rustls"] }
actix-web-actors = { version = "4.1.0", default-features = false }
opentelemetry = "0.17.0"
tracing-opentelemetry = "0.17.2"
