[package]
name = "lemmy_websocket"
version = "0.16.1"
edition = "2021"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"
homepage = "https://join-lemmy.org/"
documentation = "https://join-lemmy.org/docs/en/index.html"

[lib]
name = "lemmy_websocket"
path = "src/lib.rs"
doctest = false

[dependencies]
lemmy_utils = { version = "=0.16.1", path = "../utils" }
lemmy_api_common = { version = "=0.16.1", path = "../api_common" }
lemmy_db_schema = { version = "=0.16.1", path = "../db_schema" }
lemmy_db_views = { version = "=0.16.1", path = "../db_views" }
lemmy_db_views_actor = { version = "=0.16.1", path = "../db_views_actor" }
reqwest = { version = "0.11.7", features = ["json"] }
reqwest-middleware = "0.1.3"
tracing = "0.1.29"
rand = "0.8.4"
serde = { version = "1.0.131", features = ["derive"] }
serde_json = { version = "1.0.72", features = ["preserve_order"] }
actix = "0.13.0"
anyhow = "1.0.51"
diesel = "1.4.8"
background-jobs = "0.11.0"
tokio = "1.14.0"
strum = "0.23.0"
strum_macros = "0.23.1"
chrono = { version = "0.4.19", features = ["serde"] }
actix-web = { version = "4.0.0", default-features = false, features = ["rustls"] }
actix-web-actors = { version = "4.1.0", default-features = false }
opentelemetry = "0.16"
tracing-opentelemetry = "0.16"
