[package]
name = "lemmy_websocket"
version = "0.13.0"
edition = "2018"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"
homepage = "https://join-lemmy.org/"
documentation = "https://join-lemmy.org/docs/en/index.html"

[lib]
name = "lemmy_websocket"
path = "src/lib.rs"
doctest = false

[dependencies]
lemmy_utils = { version = "=0.13.0", path = "../utils" }
lemmy_api_common = { version = "=0.13.0", path = "../api_common" }
lemmy_db_schema = { version = "=0.13.0", path = "../db_schema" }
lemmy_db_views = { version = "=0.13.0", path = "../db_views" }
lemmy_db_views_actor = { version = "=0.13.0", path = "../db_views_actor" }
reqwest = { version = "0.11.4", features = ["json"] }
log = "0.4.14"
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0.68", features = ["preserve_order"] }
actix = "0.12.0"
anyhow = "1.0.44"
diesel = "1.4.8"
background-jobs = "0.9.0"
tokio = "1.12.0"
strum = "0.21.0"
strum_macros = "0.21.1"
chrono = { version = "0.4.19", features = ["serde"] }
actix-web = { version = "4.0.0-beta.9", default-features = false, features = ["rustls"] }
actix-web-actors = { version = "4.0.0-beta.7", default-features = false }
