---
- hosts: all

  vars_prompt:

    - name: confirm_uninstall
      prompt: "Do you really want to uninstall Lemmy? This will delete all data and can not be reverted [yes/no]"
      private: no

    - name: delete_certs
      prompt: "Delete certificates? Select 'no' if you want to reinstall Lemmy [yes/no]"
      private: no

  tasks:
  - name: end play if no confirmation was given
    debug:
      msg: "Uninstall cancelled, doing nothing"
    when: not confirm_uninstall|bool

  - meta: end_play
    when: not confirm_uninstall|bool

  - name: stop docker-compose
    docker_compose:
      project_src: /lemmy/{{domain}}/
      state: absent

  - name: delete data
    file: path={{item.path}} state=absent
    with_items:
      - { path: '/lemmy/{{domain}}/' }
      - { path: '/etc/nginx/sites-enabled/lemmy-{{ domain }}.conf' }

  - name: remove certbot cronjob
    cron:
      name=certbot-renew-lemmy
      state=absent

