version: '3.3'

services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "8540:8540"
      - "8550:8550"
      - "8560:8560"
      - "8570:8570"
      - "8580:8580"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    depends_on:
      - pictrs
      - lemmy-alpha-ui
      - lemmy-beta-ui
      - lemmy-gamma-ui
      - lemmy-delta-ui
      - lemmy-epsilon-ui

  pictrs:
    restart: always
    image: asonix/pictrs:v0.2.6-r2
    user: 991:991
    volumes:
      - ./volumes/pictrs_alpha:/mnt

  lemmy-alpha-ui:
    image: dessalines/lemmy-ui:dev
    environment:
      - LEMMY_INTERNAL_HOST=lemmy-alpha:8541
      - LEMMY_EXTERNAL_HOST=localhost:8541
      - LEMMY_HTTPS=false
    depends_on:
      - lemmy-alpha
  lemmy-alpha:
    image: lemmy-federation:latest
    volumes:
      - ./lemmy_alpha.hjson:/config/config.hjson
    environment:
      - LEMMY_TEST_SEND_SYNC=1
      - RUST_BACKTRACE=1
      - RUST_LOG="warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_queries=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
    depends_on:
      - postgres_alpha
    ports: 
      - "8541:8541"
  postgres_alpha:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_alpha:/var/lib/postgresql/data

  lemmy-beta-ui:
    image: dessalines/lemmy-ui:dev
    environment:
      - LEMMY_INTERNAL_HOST=lemmy-beta:8551
      - LEMMY_EXTERNAL_HOST=localhost:8551
      - LEMMY_HTTPS=false
    depends_on:
      - lemmy-beta
  lemmy-beta:
    image: lemmy-federation:latest
    volumes:
      - ./lemmy_beta.hjson:/config/config.hjson
    environment:
      - LEMMY_TEST_SEND_SYNC=1
      - RUST_BACKTRACE=1
      - RUST_LOG="warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_queries=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
    depends_on:
      - postgres_beta
    ports: 
      - "8551:8551"
  postgres_beta:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_beta:/var/lib/postgresql/data

  lemmy-gamma-ui:
    image: dessalines/lemmy-ui:dev
    environment:
      - LEMMY_INTERNAL_HOST=lemmy-gamma:8561
      - LEMMY_EXTERNAL_HOST=localhost:8561
      - LEMMY_HTTPS=false
    depends_on:
      - lemmy-gamma
  lemmy-gamma:
    image: lemmy-federation:latest
    volumes:
      - ./lemmy_gamma.hjson:/config/config.hjson
    environment:
      - LEMMY_TEST_SEND_SYNC=1
      - RUST_BACKTRACE=1
      - RUST_LOG="warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_queries=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
    depends_on:
      - postgres_gamma
    ports: 
      - "8561:8561"
  postgres_gamma:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_gamma:/var/lib/postgresql/data

  # An instance with only an allowlist for beta
  lemmy-delta-ui:
    image: dessalines/lemmy-ui:dev
    environment:
      - LEMMY_INTERNAL_HOST=lemmy-delta:8571
      - LEMMY_EXTERNAL_HOST=localhost:8571
      - LEMMY_HTTPS=false
    depends_on:
      - lemmy-delta
  lemmy-delta:
    image: lemmy-federation:latest
    volumes:
      - ./lemmy_delta.hjson:/config/config.hjson
    environment:
      - LEMMY_TEST_SEND_SYNC=1
      - RUST_BACKTRACE=1
      - RUST_LOG="warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_queries=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
    depends_on:
      - postgres_delta
    ports: 
      - "8571:8571"
  postgres_delta:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_delta:/var/lib/postgresql/data

  # An instance who has a blocklist, with lemmy-alpha blocked
  lemmy-epsilon-ui:
    image: dessalines/lemmy-ui:dev
    environment:
      - LEMMY_INTERNAL_HOST=lemmy-epsilon:8581
      - LEMMY_EXTERNAL_HOST=localhost:8581
      - LEMMY_HTTPS=false
    depends_on:
      - lemmy-epsilon
  lemmy-epsilon:
    image: lemmy-federation:latest
    volumes:
      - ./lemmy_epsilon.hjson:/config/config.hjson
    environment:
      - LEMMY_TEST_SEND_SYNC=1
      - RUST_BACKTRACE=1
      - RUST_LOG="warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_queries=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
    depends_on:
      - postgres_epsilon
    ports: 
      - "8581:8581"
  postgres_epsilon:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres_epsilon:/var/lib/postgresql/data
