[package]
name = "lemmy_apub_send"
publish = false
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[features]
full = [
  "lemmy_db_views_community_follower/full",
  "lemmy_db_schema/full",
  "lemmy_api_utils/full",
]

[dependencies]
lemmy_db_views_community_follower = { workspace = true }
lemmy_api_utils.workspace = true
lemmy_apub_objects.workspace = true
lemmy_db_schema = { workspace = true }
lemmy_utils.workspace = true
lemmy_db_schema_file = { workspace = true }
either.workspace = true

activitypub_federation.workspace = true
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
chrono.workspace = true
diesel = { workspace = true, features = ["chrono", "postgres", "serde_json"] }
diesel-async = { workspace = true, features = ["deadpool", "postgres"] }
reqwest.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
serde.workspace = true
tracing.workspace = true
moka.workspace = true
tokio-util = "0.7.17"
lemmy_diesel_utils = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
url.workspace = true
actix-web.workspace = true
tracing-test = "0.2.5"
uuid.workspace = true
test-context = "0.5.0"
mockall = "0.13.1"
