[package]
name = "lemmy_apub_lib"
version = "0.11.3"
edition = "2018"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"

[dependencies]
lemmy_utils = { version = "=0.11.3", path = "../utils" }
lemmy_websocket = { version = "=0.11.3", path = "../websocket" }
lemmy_apub_lib_derive = { version = "=0.11.3", path = "../apub_lib_derive" }
activitystreams = "0.7.0-alpha.11"
serde = { version = "1.0.127", features = ["derive"] }
async-trait = "0.1.51"
url = { version = "2.2.2", features = ["serde"] }
serde_json = { version = "1.0.66", features = ["preserve_order"] }
anyhow = "1.0.41"
reqwest = { version = "0.11.4", features = ["json"] }
log = "0.4.14"
